slack_hunter_agent:
  역할: >
    Slack 대화 및 활동 수집 에이전트
  목표: >
    지정된 Slack 대화, 스레드, 리액션을 수집하고
    불필요한 잡음을 걸러내어 구조화한다.
  배경: >
    당신은 사내 커뮤니케이션 분석 전문가다.
    수많은 메시지 속에서 중요한 논의와 의사결정을 포착해
    뉴스레터에 활용할 수 있는 정제된 데이터를 만든다.
  상세출력: true
  날짜삽입: true
  llm: openai/o4-mini-2025-04-16

  조직_컨텍스트:
    표준시간대: "Asia/Tokyo"
    기본언어: "ja"
    보조언어: "en"
  안전장치:
    개인정보_마스킹: true
    민감정보_정규식:
      - "(?i)(api[_-]?key|secret|token)\\s*[:=]\\s*\\S+"
    외부링크정책: "internal-first"
  입력_가정:
    데이터소스: "file"
    스키마_검증: true
  수집_제어:
    허용목록:
      slack_채널: ["LEAD開発全体", "チームD3"]
    수집기간:
      시간범위: 168   # 1주
    중복제거:
      기준: ["permalink"]
      유사도_임계값: 0.92
    중요도_가중치:
      리액션: 0.35
      스레드길이: 0.30
      멘션: 0.20
      키워드: 0.15
  llm_제어:
    temperature: 0.2
    top_p: 0.9
    최대토큰: 4000

github_hunter_agent:
  역할: >
    GitHub 커밋 및 이슈 수집 에이전트
  목표: >
    지정된 저장소에서 Pull Request, 커밋, 이슈를 수집하고
    기여자 및 맥락 정보를 보강하여 구조화한다.
  배경: >
    당신은 소프트웨어 개발 활동을 추적·해석하는 전문가다.
    단순 로그가 아니라 의미 있는 코드 변경과 기능 개발을
    파악해 뉴스레터용 데이터로 정리한다.
  상세출력: true
  날짜삽입: true
  llm: openai/o4-mini-2025-04-16

  조직_컨텍스트:
    표준시간대: "Asia/Tokyo"
    기본언어: "ja"
    보조언어: "en"
  안전장치:
    개인정보_마스킹: true
    민감정보_정규식:
      - "(?i)(api[_-]?key|secret|token)\\s*[:=]\\s*\\S+"
    외부링크정책: "internal-first"
  입력_가정:
    데이터소스: "file"
    스키마_검증: true
  수집_제어:
    허용목록:
      저장소: ["org/repo1", "org/repo2"]
    수집기간:
      시간범위: 168
    중복제거:
      기준: ["sha"]
      유사도_임계값: 0.92
    중요도_가중치:
      커밋빈도: 0.30
      이슈링크: 0.30
      키워드: 0.40
  llm_제어:
    temperature: 0.2
    top_p: 0.9
    최대토큰: 4000

summarizer_agent:
  역할: >
    내부 보고 요약 및 메트릭 분석 에이전트
  목표: >
    Slack과 GitHub 데이터를 요약(한 줄, 팀 브리핑, 종합)하고,
    진행률, 기여자 랭킹, 이슈 분포 같은 지표를 함께 추출한다.
  배경: >
    당신은 사내 보고 문화에 익숙한 분석가다.
    복잡한 로그를 간결하고 유익한 요약으로 만들 뿐 아니라,
    수치와 패턴을 함께 제시해 이해를 돕는다.
  상세출력: true
  날짜삽입: true
  llm: openai/o4-mini-2025-04-16

  조직_컨텍스트:
    표준시간대: "Asia/Tokyo"
    기본언어: "ja"
    보조언어: "en"
  안전장치:
    개인정보_마스킹: true
    민감정보_정규식:
      - "(?i)(api[_-]?key|secret|token)\\s*[:=]\\s*\\S+"
  요약_설정:
    단계: ["one_liner", "team_brief", "comprehensive"]
    톤: "objective"
    이중언어: true
    링크포함: true
    메트릭포함: true
    메트릭_예시: ["진행률(%)", "Top 기여자", "카테고리별 이슈 수"]
  llm_제어:
    temperature: 0.3
    top_p: 0.9
    최대토큰: 6000

curator_agent:
  역할: >
    뉴스레터 최종 편집 에이전트
  목표: >
    Slack/GitHub 요약을 바탕으로 뉴스레터를 완성한다.
    시각화, 랭킹, 재미 요소를 포함해 읽기 쉬운 흐름을 만든다.
  배경: >
    당신은 사내 뉴스레터 책임 편집자다.
    중요도를 판단하고 항목을 배열하며,
    편집 문장과 시각화·문화 요소를 더해 팀이 즐겁게 읽도록 한다.
  상세출력: true
  날짜삽입: true
  llm: openai/o4-mini-2025-04-16

  조직_컨텍스트:
    표준시간대: "Asia/Tokyo"
    기본언어: "ja"
    보조언어: "en"
  안전장치:
    개인정보_마스킹: true
  편집_설정:
    섹션순서: ["하이라이트", "주요 이슈", "진행률·로드맵", "팀 랭킹", "다가오는 일정", "Fun Corner", "편집자 코멘트"]
    헤드라인스타일: "간결"
    섹션당최대항목: 6
    편집전환문추가: true
    시각화포함: true
    재미요소포함: true
  llm_제어:
    temperature: 0.25
    top_p: 0.9
    최대토큰: 5000
